# Migration Guide: v1 → v2 Tool Port

The v2 toolkit fully implements four new tools (Pre-Analysis Plan, Bias Check,
KM Diagnostics, STROBE+RECORD) and migrates two representative existing tools
(Outcomes Table, Forest Plot) to the v2 standardized pattern. The remaining
seven v1 tools follow the same template; this guide describes the exact
changes required for each.

## The v2 standardized template

Every v2 page MUST follow this skeleton:

```python
import streamlit as st
import pandas as pd

# 1. Shared imports
from utils.session import (
    ensure_context,
    render_context_banner,
    render_methods_text,
    render_check_callout,
    render_source_check,
    register_upload,
    list_uploads,
)
from utils.parsers import (
    parse_baseline_csv, parse_moa_csv, parse_km_csv,
    detect_export_type, EXPORT_BASELINE, EXPORT_MOA, EXPORT_KM,
)
from utils.formatters import (
    fmt_p, fmt_pct, fmt_ratio_with_ci, fmt_smd, fmt_count_pct,
    safe_float, safe_int, crosses_null, is_significant,
)
from utils.figure_defaults import (
    palette_colors, preset_size, FONT_CHOICES, PALETTES, FIGURE_PRESETS,
    DEFAULT_DPI, NULL_LINE_COLOR,
)
from utils.exports import (
    render_figure_downloads, render_table_downloads,
    render_reproducibility_footer,
)

# 2. Page config + title
st.set_page_config(page_title="...", page_icon="...", layout="wide")
ctx = ensure_context()
st.title("...")
st.caption("One-sentence description.")

# 3. Context banner (always present)
render_context_banner()  # show_advanced=True only on Home

# 4. Required-input expander
# 5. Upload block with session reuse
# 6. Parsed-summary banner
# 7. Edit-before-output data editor
# 8. Sidebar visual controls (figure tools only)
# 9. Output preview
# 10. Download buttons via shared exports
# 11. Verify-against-source widget
# 12. Auto-generated narrative paragraph
# 13. render_check_callout(...)
# 14. render_methods_text(...)
# 15. render_reproducibility_footer("Tool name")
```

## Per-tool migration notes

### 03_❤️_Love_Plot.py — Phase 2

**v1 file:** `pages/6_❤️_Love_Plot_Generator.py`

**Changes required:**

1. Replace the page-local `load_trinetx_baseline()` function with a single
   call to `parse_baseline_csv()` from `utils.parsers`. This gives the same
   DataFrame plus `has_smd_columns`, `cohort_1_label`, and `source_excerpt`
   for the verify-against-source widget.

2. Replace `find_smd_columns()` with `df[["Before: Standardized Mean
   Difference", "After: Standardized Mean Difference"]]`. The parser
   already standardizes column names.

3. Read color choices from `palette_colors(ctx.palette)` instead of letting
   the user pick from `C0`/`C1`. The user can override via the sidebar
   palette selector, but the default comes from session context.

4. Register the upload via `register_upload(file_id, name, raw_bytes,
   EXPORT_BASELINE)` so the PSM Table tool reuses the same file in the
   same session.

5. Replace `st.download_button` for the PNG with
   `render_figure_downloads(fig, prefix="love_plot")` so SVG is offered too.

6. Add `render_source_check("SMD columns parsed from {name}", df_sample)`
   showing the first 10 covariate rows from the parsed DataFrame.

7. Add `render_check_callout("If important covariates remain above the |SMD|
   threshold after matching, document the residual imbalance in the
   Limitations section.")`.

8. Add `render_methods_text("Covariate balance was assessed using a Love
   plot generated by the Love Plot tool of the TriNetX Publication Toolkit
   v2. Before and after propensity score matching, the mean |SMD| was X
   and Y, with N1 / N covariates and N2 / N covariates above the
   pre-specified threshold of {threshold:.2f}.")`.

9. Add `render_reproducibility_footer("Love Plot")` at the end.

**Estimated lines changed:** ~60 lines (out of ~700 in v1).

### 04_⚖️_PSM_Table.py — Phase 2

**v1 file:** `pages/7_⚖️_PSM_Table_Generator.py`

**Changes required:**

1. Replace `read_trinetx_baseline_csv` with `parse_baseline_csv` from
   `utils.parsers`.
2. Pull cohort labels from `ctx` instead of user-typed text inputs (let
   the user override on the context banner instead).
3. Pull decimal preferences from `ctx.pct_decimals`, `ctx.smd_decimals`,
   `ctx.ratio_decimals`.
4. Use `fmt_count_pct`, `fmt_mean_sd`, `fmt_smd`, `fmt_p` from
   `utils.formatters` instead of locally defined formatters.
5. Replace HTML/CSV/DOCX export with `render_table_downloads`.
6. Add `render_source_check`, `render_check_callout`,
   `render_methods_text`, `render_reproducibility_footer`.

The DOCX builder in v1 is one of the strongest pieces of code in the v1
toolkit — keep it largely intact but read fonts and decimals from `ctx`
rather than from per-page form fields.

**Estimated lines changed:** ~120 lines (out of ~1400 in v1).

### 07_📊_Two-Cohort_Bar.py — Phase 3

**v1 file:** `pages/5_📊_Two-Cohort Outcome Bar Graphs.py`

**Changes required:**

1. Replace the page-local MOA parser with `parse_moa_csv` from
   `utils.parsers`.
2. Pull color palette from `figure_defaults.PALETTES` instead of the
   local `PALETTES` dictionary (the v1 dictionary was the foundation for
   the v2 module — same colors, now centrally available).
3. Pull cohort labels from `ctx`.
4. Replace local Wilson CI computation by calling out to a shared
   `utils.stats.wilson_ci()` (add this helper if needed; currently the v1
   implementation is fine but should be moved to `utils/stats.py`).
5. Standard downloads, source check, methods text, footer.

**Estimated lines changed:** ~100 lines.

### 08_📉_Kaplan_Meier_Curve.py — Phase 3

**v1 file:** `pages/3_📉_Kaplan_Meier_Curve_Maker.py`

**Changes required:**

1. Replace the inline `pd.read_csv` + column-cleaning with
   `parse_km_csv()`.
2. The v1 implementation does in-page ffill on survival columns — the
   parser does this now, so remove the duplicate logic.
3. Cohort labels and colors from `ctx`.
4. Add a footer link from this page to the KM Diagnostics tool (new tool
   B) so users know to run the PH check before submitting the curve.
5. Standard downloads, source check, methods text, footer.

**Estimated lines changed:** ~80 lines.

### 09_🎯_Power_E-value_NNT.py — Phase 4

**v1 file:** `pages/2_🎯_Power & Sample Size Adequacy Calculator.py`

**Changes required:**

1. Replace the hard-coded MOA row indices (`arr[10, 2]`, etc.) with calls
   to `parse_moa_csv()`. **This is the single most important change in
   the migration.** The v1 code assumed a fixed layout that breaks
   silently if TriNetX shifts its export.
2. Read `alpha`, `power_target`, `outcome_is_adverse`, and
   `treated_cohort` from `ctx` instead of from per-page sidebar widgets
   (still allow override).
3. Use `fmt_p`, `fmt_pct`, `fmt_ratio` from `utils.formatters`.
4. Keep the narrative-explanation generator — it is the best example in
   the v1 toolkit of a per-row Methods text snippet.
5. Add source check, methods text, footer.

**Estimated lines changed:** ~150 lines.

### 10_📐_Effect_Size.py — Phase 4

**v1 file:** `pages/1_📐_Effect_Size_Calculator.py`

**Changes required:**

1. This tool accepts manual entry, not TriNetX files, so the parser layer
   does not apply.
2. Use the shared palette/font/figure-preset for the forest plot output.
3. Use `fmt_p`, `fmt_ratio`, `fmt_ci` for display.
4. Standard downloads, methods text, footer.

**Estimated lines changed:** ~50 lines.

### 11_📊_Multiple_Comparisons.py — Phase 4

**v1 file:** `pages/10_Multiple_Comparison_Calculator.py`

**Changes required:**

1. Replace the inline MOA parser (`parse_trinetx_moa_text`) with
   `parse_moa_csv()`.
2. Read `alpha` and `multiple_comparison_family` from `ctx`.
3. Register MOA uploads to share with the Outcomes Table and Forest Plot
   tools.
4. Standard downloads, source check, methods text, footer.

**Estimated lines changed:** ~70 lines.

## A note on the v1 STROBE tool

The v1 `8_📝_Novak's_STROBE_Assessment_Tool.py` is **replaced by, not
migrated to**, the v2 STROBE + RECORD tool. Existing scores can be
preserved by re-running the v2 tool — the items are a superset of the
v1 STROBE items.

## Total effort

The migration guide above describes ~750 lines of changes across seven
v1 files, totaling well under 10% of the v1 codebase. Most of the
remaining v1 code (parsing logic, formatting helpers, MOA-section
extraction) is now in `utils/` and is shared rather than duplicated.

The result is a toolkit where:

- A bug fix in a parser propagates to every tool that uses it
- The cohort direction is set once and applied everywhere
- The same uploaded file is consumed by every tool that needs it
- Every output has the same look-and-feel and the same set of downloads
- Every output ends with a verify-against-source widget, a methods text
  block, and a check callout — without each tool having to implement those
  patterns separately

This is what makes the v2 toolkit a coherent system rather than a
collection of scripts.
